config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stations, only: [:index]
  resources :conditions, only: %i[index show]
  resources :users, only: [:new, :create]
  get '/account', to: 'users#edit', as: 'edit_user'
  patch '/account/update', to: 'users#update', as: 'user'

  namespace :admin do
    resources :stations, except: %i[index show]
    resources :trips, except: %i[index show]
    resources :accessories, path: 'bike-shop', only: [:index, :new, :create, :edit, :update]
    resources :conditions, except: %i[index show]
    resources :orders, only: %i[show update]
    get '/dashboard', to: 'dashboard#index'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/cart', to: 'cart#index'
  post '/cart', to: 'cart#create'
  patch '/cart', to: 'cart#update'
  delete '/cart', to: 'cart#destroy'

  get '/dashboard', to: 'users#dashboard'
  get '/conditions-dashboard', to: 'conditions#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/trips-dashboard', to: 'trips#dashboard'

  resources :trips, only: [:index, :show]
  resources :accessories, path: 'bike-shop', only: [:show, :index]
  resources :orders
  get '/:name', to: 'stations#show'
end

app/models/station.rb
class Station < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_presence_of :name, :dock_count, :city, :installation_date
  has_many :start_trips, class_name: 'Trip', foreign_key: 'start_station_id', dependent: :destroy
  has_many :end_trips, class_name: 'Trip', foreign_key: 'end_station_id', dependent: :destroy

  def self.avg_bikes
    average(:dock_count).to_i
  end

  def self.max_bike_count
    maximum(:dock_count)
  end

  def self.max_bikes
    where(dock_count: maximum(:dock_count))
  end

  def self.min_bike_count
    minimum(:dock_count)
  end

  def self.min_bikes
    where(dock_count: minimum(:dock_count))
  end

  def self.newest
    find_by(installation_date: maximum(:installation_date))
  end

  def self.oldest
    find_by(installation_date: minimum(:installation_date))
  end

  def most_frequent_destination
    start_trips
      .select('end_station_id, COUNT(end_station_id) AS count')
      .group(:end_station_id)
      .order('count DESC')
      .first
      .end_station
  end

  def most_frequent_origin
    end_trips
      .select('start_station_id, COUNT(start_station_id) AS count')
      .group(:start_station_id)
      .order('count DESC')
      .first
      .start_station
  end

  def date_with_most_trips
    start_trips
      .select('date(trips.start_date) as date, count(date(start_date)) AS count')
      .group('date(start_date)')
      .to_a
      .first
      .date
      .to_date
  end

  def most_frequent_zip_code
    start_trips
      .select('zip_code, count(zip_code) AS count')
      .group(:zip_code)
      .to_a
      .first
      .zip_code
  end

  def most_frequent_bike
    start_trips
      .select('bike_id, count(bike_id) AS count')
      .group(:bike_id)
      .to_a
      .first
      .bike_id
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController
  before_action :set_station, except: %i[new create]

  def edit
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:success] = "#{@station.name} created!"
      redirect_to "/#{@station.slug}"
    else
      flash[:error] = 'Station not created!'
      render :new
    end
  end

  def update
    @station.slug = nil
    if @station.update(station_params)
      flash[:success] = "#{@station.name} updated!"
      redirect_to "/#{@station.slug}"
    else
      flash[:error] = "#{@station.name} not updated!"
      render :edit
    end
  end

  def destroy
    name = @station.name
    if @station.destroy
      flash[:success] = "#{name} Deleted!"
      redirect_to stations_path
    else
      flash[:error] = "#{name} Not Deleted"
      redirect_to "/#{@station.slug}"
    end
  end

  private

  def station_params
    params.require(:station).permit(:name,
                                    :dock_count,
                                    :city,
                                    :installation_date)
  end

  def set_station
    @station = Station.find_by_slug(params[:id])
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :require_login, only: [:dashboard]

  def index
    @stations = Station.all
  end

  def show
    @station = Station.find_by(slug: params[:name])
  end

  def dashboard
    @num_stations = Station.count
    @avg_bikes = Station.avg_bikes
    @max_bikes = Station.max_bike_count
    @max_bikes_stations = Station.max_bikes

    @min_bikes = Station.min_bike_count
    @min_bikes_stations = Station.min_bikes

    @newest_station = Station.newest
    @oldest_station = Station.oldest
  end
end

app/views/stations/dashboard.html.erb
<section class='title'>
  <h1>Stations Dashboard</h1>
</section>

<section class='title'>
  <h3>Total Number of Stations: <%= @num_stations %></h3>
</section>

<section class='title'>
  <h3>Average number of bikes: <%= @avg_bikes %></h3>
</section>

<section class='title'>
  <h3>Maximum bikes available: <%= @max_bikes %></h3>
</section>

<section class='title'>
  <h3>Stations with <%= @max_bikes %> bikes</h3>
</section>
<table id="most_bikes">
  <tr>
    <th>Name</th>
  </tr>
  <% @max_bikes_stations.each do |station| %>
    <tr>
      <td>
        <%= link_to station.name, station.slug %>
      </td>
    </tr>
  <% end %>
</table>

<section class='title'>
  <h3>Minimum bikes available: <%= @min_bikes %></h3>
</section>

<section class='title'>
  <h3>Stations with <%= @min_bikes %> bikes</h3>
</section>
<table id="fewest_bikes">
  <tr>
    <th>Name</th>
  </tr>
  <% @min_bikes_stations.each do |station| %>
    <tr>
      <td>
        <%= link_to station.name, station.slug %>
      </td>
    </tr>
  <% end %>
</table>

<section class='title'>
  <h3>Newest station: <%= link_to @newest_station.name, @newest_station.slug %></h3>
</section>

<section class='title'>
  <h3>Oldest station: <%= link_to @oldest_station.name, @oldest_station.slug %></h3>
</section>

app/views/stations/index.html.erb
<section class = 'title'>
  <h1>All Stations</h1>
</section>
<section class = 'title'>
<% if current_user %>
  <h3><%= link_to '>>>>Go to Stations Dashboard', stations_dashboard_path %></h3>
<% end %>
</section>
<section class = 'title'>
  <% if current_admin? %>
    <p><%= link_to 'Add a New Station!', new_admin_station_path %></p>
  <% end %>
</section>

<table>
  <tr>
    <th>Name</th>
    <th>Dock Count</th>
    <th>City</th>
    <th>Installation Date</th>
    <% if current_admin? %>
      <th>Edit</th>
      <th>Delete</th>
    <% end %>
  </tr>
  <% @stations.each do |station| %>
    <tr class=station_<%= station.id %>>
      <td><%= link_to station.name, "/#{station.slug}" %></td>
      <td align='right'><%= station.dock_count %></td>
      <td align='right'><%= station.city %></td>
      <td align='right'><%= station.installation_date.strftime('%d %B %Y') %></td>
      <% if current_admin? %>

      <td><%= link_to edit_admin_station_path(station) do %>
          <i class="far fa-edit"></i>
      <% end %></td>

      <td><%= link_to admin_station_path(station), method: 'delete' do %>
          <i class="fas fa-trash-alt"></i>
      <% end %></td>

      <% end %>
    </tr>
  <% end %>
</table>

app/views/stations/show.html.erb
<div class="class=station_<%= @station.id %>">
  <section class='title'>
    <h1><%= @station.name %></h1>
  </section>
  <section class='main'>
    <h4>Dock Count: <%= @station.dock_count %></h4>
    <h4>City: <%= @station.city %></h4>
    <h4>Installation Date: <%= @station.installation_date.strftime('%d %B %Y') %></h4>

    <% if current_admin? %>
      <p><%= link_to edit_admin_station_path(@station) do %>
          <i class="far fa-edit"></i>
      <% end %></p>

      <p><%= link_to admin_station_path(@station), method: 'delete' do %>
          <i class="fas fa-trash-alt"></i>
      <% end %></p>
    <% end %>
    <% if current_user %>
      <h4>Trips from here: <%= @station.start_trips.length %></h4>
      <h4>Trips to here: <%= @station.end_trips.length %></h4>

      <% if @station.start_trips.length > 0 %>
        <h4>
          Most frequent destination: <%= link_to @station.most_frequent_destination.name, "/#{@station.most_frequent_destination.slug}" %>
        </h4>
      <% end %>
      <% if @station.end_trips.length > 0 %>
        <h4>
          Most frequent origin: <%= link_to @station.most_frequent_origin.name, "/#{@station.most_frequent_origin.slug}" %>
        </h4>
      <% end %>
      <% if @station.start_trips.length > 0 %>
        <h4>Date with most trips from here: <%= @station.date_with_most_trips.strftime('%d %B %Y') %></h4>
        <h4>Most frequent zip code for users of this station: <%= @station.most_frequent_zip_code %></h4>
        <h4>Most frequently used bike at this station: <%= @station.most_frequent_bike %></h4>
      <% end %>
    <% end %>
    <%= link_to '<< Back to Station Index', stations_path %>
  </div>
</section>