config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stations, only: [:index]
  resources :conditions, only: %i[index show]
  resources :users, only: [:new, :create]
  get '/account', to: 'users#edit', as: 'edit_user'
  patch '/account/update', to: 'users#update', as: 'user'

  namespace :admin do
    resources :stations, except: %i[index show]
    resources :trips, except: %i[index show]
    resources :accessories, path: 'bike-shop', only: [:index, :new, :create, :edit, :update]
    resources :conditions, except: %i[index show]
    resources :orders, only: %i[show update]
    get '/dashboard', to: 'dashboard#index'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/cart', to: 'cart#index'
  post '/cart', to: 'cart#create'
  patch '/cart', to: 'cart#update'
  delete '/cart', to: 'cart#destroy'

  get '/dashboard', to: 'users#dashboard'
  get '/conditions-dashboard', to: 'conditions#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/trips-dashboard', to: 'trips#dashboard'

  resources :trips, only: [:index, :show]
  resources :accessories, path: 'bike-shop', only: [:show, :index]
  resources :orders
  get '/:name', to: 'stations#show'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
    @orders = Order.all
    @orders_by_status = orders_by_status
  end

 private

   def orders_by_status
    Order.where(status: params[:status])
   end
end

app/views/admin/dashboard/index.html.erb
<section class='title'>
<h1> Admin Dashboard</h1>
</section>

<section class="admin">
  <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
  <p><%= current_user.address %></p>
  Something look wrong here? <%= link_to 'Edit Your Info', edit_user_path(current_user)%>
</section>
<br>
<br>
<section class='title'>
  <%= link_to 'View All Accessories', admin_accessories_path %>
</section>
<br>

<section class='title'>
  <h3> Total Number of Orders by Status</h3>
</section>
<br>
<section class="admin">
  <%= link_to 'Ordered', admin_dashboard_path(status: 'Ordered') %>: <%= @orders.ordered_count %>
  <%= link_to 'Paid', admin_dashboard_path(status: 'Paid') %>: <%= @orders.paid_count %>
  <%= link_to 'Cancelled', admin_dashboard_path(status: 'Cancelled') %>: <%= @orders.cancelled_count %>
  <%= link_to 'Completed', admin_dashboard_path(status: 'Completed') %>: <%= @orders.completed_count %>
</section>

<section class="admin">
<% if @orders_by_status.empty? %>
  <section>
    <h3> All Orders</h3>
  </section>
  <ul class='no-bullets'>
    <% @orders.each do |order| %>
      <li>
        <%= link_to "Order ##{order.id}", admin_order_path(order) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <section>
    <h3> All Orders with Status: <%= @orders_by_status.first.status %></h3>
  </section>
  <ul>
  <% @orders_by_status.each do |order| %>
    <div class="order_<%=order.id%>">
      <%= link_to "Order ##{order.id} ", admin_order_path(order) %>
      <% if order.status == 'Ordered'%>
        | <%= link_to 'Mark as Paid', admin_order_path(order, status: 'Paid'), method: 'Put'  %>
        | <%= link_to 'Cancel', admin_order_path(order, status: 'Cancelled'), method: 'Put'%>
      <% elsif order.status == 'Paid' %>
      | <%= link_to 'Mark as Completed', admin_order_path(order, status: 'Completed'), method: 'Put'  %>
      | <%= link_to 'Cancel', admin_order_path(order, status: 'Cancelled'), method: 'Put'%>
      <% end %>
    </div>
  <% end %>
</ul>
<% end %>
</section>