config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stations, only: [:index]
  resources :conditions, only: %i[index show]
  resources :users, only: [:new, :create]
  get '/account', to: 'users#edit', as: 'edit_user'
  patch '/account/update', to: 'users#update', as: 'user'

  namespace :admin do
    resources :stations, except: %i[index show]
    resources :trips, except: %i[index show]
    resources :accessories, path: 'bike-shop', only: [:index, :new, :create, :edit, :update]
    resources :conditions, except: %i[index show]
    resources :orders, only: %i[show update]
    get '/dashboard', to: 'dashboard#index'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/cart', to: 'cart#index'
  post '/cart', to: 'cart#create'
  patch '/cart', to: 'cart#update'
  delete '/cart', to: 'cart#destroy'

  get '/dashboard', to: 'users#dashboard'
  get '/conditions-dashboard', to: 'conditions#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/trips-dashboard', to: 'trips#dashboard'

  resources :trips, only: [:index, :show]
  resources :accessories, path: 'bike-shop', only: [:show, :index]
  resources :orders
  get '/:name', to: 'stations#show'
end

app/views/partials/_nav.html.erb
<nav>
    <ul class="nav-left">
      <div class="brand-logo">
        <i class="fas fa-bicycle"></i>
        <% if current_admin? %>
          <a href="/admin/dashboard">Bike Share</a>
        <% elsif current_user %>
          <a href="/dashboard">Bike Share</a>
        <% else %>
          <a href="/">Bike Share</a>
        <% end %>
      </div>
    </ul>
    <div class='nav-right'>
      <% if current_admin? %>
      <div class='nav-link'>
        <%= link_to 'Bike Shop', admin_accessories_path %>
      </div>
      <% else %>
      <div class='nav-link'>
        <%= link_to 'Bike Shop', accessories_path %>
      </div>
      <% end %>
      <div class='nav-link'>
        <%= link_to 'Trips', trips_path %>
      </div>
      <div class='nav-link'>
        <%= link_to 'Stations', stations_path %>
      </div>
      <div class='nav-link'>
        <%= link_to 'Conditions', conditions_path %>
      </div>
      <div class='nav-link'>
        <%= link_to "Cart: #{@cart.total_count}", cart_path %>
      </div>
      <div class="nav-link">
        <% if current_user %>
          <%= link_to 'Logout', logout_path %>
        <% else %>
          <%= link_to 'Login', login_path %>
        <% end %>
      </div>
    </div>
</nav>

<section class='flash'>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, sanitize(msg), class: name %>
  <% end %>
</section>

app/views/partials/nav.html.erb
<nav>
  <ul class="nav-bar">
    
  </ul>
</nav>