config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stations, only: [:index]
  resources :conditions, only: %i[index show]
  resources :users, only: [:new, :create]
  get '/account', to: 'users#edit', as: 'edit_user'
  patch '/account/update', to: 'users#update', as: 'user'

  namespace :admin do
    resources :stations, except: %i[index show]
    resources :trips, except: %i[index show]
    resources :accessories, path: 'bike-shop', only: [:index, :new, :create, :edit, :update]
    resources :conditions, except: %i[index show]
    resources :orders, only: %i[show update]
    get '/dashboard', to: 'dashboard#index'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/cart', to: 'cart#index'
  post '/cart', to: 'cart#create'
  patch '/cart', to: 'cart#update'
  delete '/cart', to: 'cart#destroy'

  get '/dashboard', to: 'users#dashboard'
  get '/conditions-dashboard', to: 'conditions#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/trips-dashboard', to: 'trips#dashboard'

  resources :trips, only: [:index, :show]
  resources :accessories, path: 'bike-shop', only: [:show, :index]
  resources :orders
  get '/:name', to: 'stations#show'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :username
  validates_presence_of :password, confirmation: true
  validates_uniqueness_of :username

  enum role: %w[default admin]
  has_many :orders

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:dashboard, :edit, :update]
  before_action :set_user, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = "Logged in as #{user.username}"
      redirect_to '/dashboard'
    else
      redirect_to new_user_path
    end
  end

  def dashboard
  end

  def edit
    @user = current_user
  end

  def update
    if @user == current_user && @user.update(user_params)
      flash[:success] = "#{@user.username}, your account has been updated!"
      redirect_to dashboard_path
    else
      flash[:error] = "#{@user.username}, your account didn't update."
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :password,
                                 :password_confirmation,
                                 :first_name,
                                 :last_name,
                                 :address)
  end

  def set_user
    @user = current_user
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <h1>Account Info:</h1>

  <div class='form_field'>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class='form_field'>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class='form_field'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <h2>Personal Info</h2>

  <div class='form_field'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class='form_field'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class='form_field'>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <%= f.submit 'Submit' %>
<% end %>

app/views/users/dashboard.html.erb
<div class="title">
<h1>Welcome <%= current_user.username %></h1>
</div>
<section class="admin">
<h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
<p><%= current_user.address %></p>
Something look wrong here? <%= link_to 'Edit Your Info', edit_user_path(current_user)%>


<div class="orders">
  <% if current_user.orders.empty? %>
    Looks like you haven't placed any orders yet. Come check out our <%= link_to 'Bike Shop', accessories_path %>!
    <% end %>
  <% current_user.orders.each do |order| %>
    <div id="order_<%= order.id %>">
      <%= link_to "Order ##{order.id}", order_path(order) %>: $<%= order.total %>.00
    </div>
  <% end %>
</div>
</section>

app/views/users/edit.html.erb
<section class='title'>
  <h1>Edit Your Info, <%= current_user.username %></h1>
</section>
<%= render partial: 'form' %>

app/views/users/new.html.erb
<%= render partial: 'form' %>